### ISSUE TITLE
Crash when open setting

### ISSUE THREAD

**Issue by muhammadarif1** [z3r0c00l-2k/AquaDroid#22]
Android 5.1

```FATAL EXCEPTION: main
Process: io.github.z3r0c00l_2k.aquadroid, PID: 14180
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.media.Ringtone.getTitle(android.content.Context)' on a null object reference
	at io.github.z3r0c00l_2k.aquadroid.fragments.BottomSheetFragment.onViewCreated(BottomSheetFragment.kt:61)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)``

**Comment by z3r0c00l-2k** [comment]
Can you provide more details ?

**Comment by z3r0c00l-2k** [comment]
closing this issue due to inactivity
